# Generated by Django 4.2.10 on 2024-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0006_pipelineexecutionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecutionrecord',
            name='logs',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
