# Generated by Django 4.2.10 on 2024-02-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0007_alter_pipelineexecutionrecord_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutionrecord',
            name='pipeline_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_configuration.pipelinerun'),
        ),
    ]
