# Generated by Django 4.2.10 on 2024-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0008_pipelineexecutionrecord_pipeline_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
