# Generated by Django 4.2.10 on 2024-03-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_configuration", "0009_workflow_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
