# Generated by Django 4.2.10 on 2024-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_configuration", "0010_version_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="specyaml",
            name="document",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="specyaml",
            name="document_link",
            field=models.URLField(null=True),
        ),
    ]
