# Generated by Django 4.2.10 on 2024-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0012_alter_pipelineexecutionrecord_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specyaml',
            name='document_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
