# Generated by Django 4.2.10 on 2024-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0017_secrettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineexecutionrecord',
            name='logs',
        ),
        migrations.AddField(
            model_name='pipelineexecutionrecord',
            name='job_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionrecord',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
