# Generated by Django 4.2.10 on 2024-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_configuration", "0019_pipelineyamlhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineexecutionrecord",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pipelineexecutionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("TRIGGERED", "TRIGGERED"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                    ("ERROR", "ERROR"),
                ],
                default="COMPLETED",
                max_length=255,
            ),
        ),
    ]
