# Generated by Django 4.2.10 on 2024-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_configuration', '0021_alter_pipelineexecutionrecord_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineyamlhistory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
